name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment
        run: echo "Deploying to ${{ github.event.inputs.environment }}"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH private key as a secret in GitHub

      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H bernardosecades.com >> ~/.ssh/known_hosts          

      - name: Deploy to Server - API
        env: # Pass your secrets as environment variables
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
        run: ./scripts/deploy_api.sh
      - name: Deploy to Server - SWAGGER UI
        run: ./scripts/deploy_swagger_ui.sh
